services:
- type: web
  name: bassam-smart-ai
  runtime: python
  region: oregon
  plan: free

  buildCommand: pip install --upgrade pip && pip install -r requirements.txt
  startCommand: gunicorn -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --workers 1 --timeout 120 main:app

  envVars:
  - key: PYTHON_VERSION
    value: 3.11.7
  - key: PYTHONUNBUFFERED
    value: "1"
  - key: WEB_CONCURRENCY
    value: "1"

  # صحّح مسار الصحة ليتطابق مع الكود
  healthCheckPath: /healthz

  # قرص مؤقت (اختياري وخفيف)
  disk:
    name: bassam-cache
    mountPath: /opt/render/project/src/cache
    sizeGB: 1
